/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-19 09:27:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lesson;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import tomato.lesson.*;
import tomato.member.*;

public final class lessonList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1633071175604L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1634624681575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("tomato.lesson");
    _jspx_imports_packages.add("tomato.member");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      tomato.lesson.LessonDAO ldao = null;
      synchronized (session) {
        ldao = (tomato.lesson.LessonDAO) _jspx_page_context.getAttribute("ldao", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (ldao == null){
          ldao = new tomato.lesson.LessonDAO();
          _jspx_page_context.setAttribute("ldao", ldao, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tomato/css/mainLayout.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("      background: #f5f4f0;\r\n");
      out.write("      font-family: 'Roboto';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3{\r\n");
      out.write("   text-align: center!important;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lessonTable {\r\n");
      out.write("   background-color:white;\r\n");
      out.write("   border:1px solid tomato;\r\n");
      out.write("   width: 750px;\r\n");
      out.write("   margin: 0px auto;\r\n");
      out.write("   padding:15px;   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lessonTable a{ \r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lessonTable a:link ,.lessonTable a:visited ,.lessonTable a:hover{ \r\n");
      out.write("    color: #000;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("li{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("   color: white; \r\n");
      out.write("   font-size:20px; \r\n");
      out.write("   font-weight: bold; \r\n");
      out.write("   background-color: tomato; \r\n");
      out.write("   height:30px;\r\n");
      out.write("   width:200px; \r\n");
      out.write("   padding:10px; \r\n");
      out.write("   text-align:center;\r\n");
      out.write("   margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".enddate{\r\n");
      out.write("   text-align:right;\r\n");
      out.write("}\r\n");
      out.write(".l_name{\r\n");
      out.write("   font-size: 35px;\r\n");
      out.write("   text-align: eft;\r\n");
      out.write("   font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write(".l_title{\r\n");
      out.write("   font-size:15px;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".l_people{\r\n");
      out.write("   text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchBar{\r\n");
      out.write("   text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinbt{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 0px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinbt:hover{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#joinbtn4{\r\n");
      out.write("   background-color:white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none; tomato;\r\n");
      out.write("}\r\n");
      out.write("meter {\r\n");
      out.write("	width: 250px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#btn1{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#btn1:hovertn1{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");

String m_id=(String)session.getAttribute("m_id");
String m_name=(String)session.getAttribute("m_name");
if(m_id==null){
   
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   <a href=\"/tomato/member/login.jsp\">로그인</a> | <a href=\"/tomato/member/join.jsp\">회원가입</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
 
}else{
      
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   ");

   if(m_id.equals("admin")){
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/admin/memberList_admin.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }else{
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/member/mypage.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }
   
      out.write("\r\n");
      out.write("   <a href=\"/tomato/member/logout.jsp\">로그아웃</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");

}

      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><h1><a href=\"/tomato/index.jsp\"><img src=\"/tomato/img/토마토_메인로고.png\" alt=\"메인로고\" height=\"50px\" width=\"250px\"></a></h1></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/sell/sell.jsp\">SELL</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/buy/buyList.jsp?col=s_idx&range=desc\">BUY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/lesson/lessonList.jsp\">LESSON</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/community/community.jsp\">COMMUNITY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/qna/qnaList.jsp\">Q&A</a></h2></li>\r\n");
      out.write("   <li>\r\n");
      out.write("		<form name=\"headerSearch\" action=\"/tomato/buy/headerBuySearch.jsp\" style=\"display: inline;\">\r\n");
      out.write("			<input type=\"text\" name=\"searchValue\" placeholder=\"상품을 검색하세요\">\r\n");
      out.write("			<input type=\"submit\" value=\"검색\" id=\"btn1\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<hr/>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

MemberDTO mdto=ldao.selectAllm(m_id); 
ldao.lessonOk();

/**비회원 리스트 접속시, 모든 지역 레슨리스트 보이게*/
/**전체 레슨 페이징*/
int totalCnt=0;
if(m_id==null||m_id.equals("")||m_id.equals("admin")){
		totalCnt=ldao.getTotalCnt();
}else{
		totalCnt=ldao.getTotalCnt(mdto.getM_addr());
}
int listSize=5;
int pageSize=3;

String cp_s=request.getParameter("cp");
if(cp_s==null||cp_s.equals("")){
	cp_s="1";
}
int cp=Integer.parseInt(cp_s);

int totalPage=(totalCnt/listSize)+1;
if(totalCnt%listSize==0)totalPage--;

int userGroup=cp/pageSize;
if(cp%pageSize==0)userGroup--;
/**------------------------------------------------------------*/
/**인기 레슨 페이징*/
int pop_totalCnt=0;
if(m_id==null||m_id.equals("")||m_id.equals("admin")){
	pop_totalCnt=ldao.getPopularTotalCnt();
}else{
	pop_totalCnt=ldao.getPopularTotalCnt(mdto.getM_addr());
}
int pop_listSize=1;
int pop_pageSize=1;

String pop_cp_s=request.getParameter("pop_cp");
if(pop_cp_s==null||pop_cp_s.equals("")){
	pop_cp_s="1";
}
int pop_cp=Integer.parseInt(pop_cp_s);

int pop_totalPage=(pop_totalCnt/pop_listSize)+1;
if(pop_totalCnt%pop_listSize==0)pop_totalPage--;

int pop_userGroup=pop_cp/pop_pageSize;
if(pop_cp%pop_pageSize==0)pop_userGroup--;

      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("	<article>\r\n");
      out.write("	");

	String userAddr;
	if(m_id==null||m_id.equals("")||m_id.equals("admin")){ 
		userAddr="전체지역";
	}else{
		userAddr=mdto.getM_addr();
	}
	
      out.write("\r\n");
      out.write("		<h3 style=\"color:tomato; text-align:left;\">");
      out.print(userAddr );
      out.write(" 레슨</h3>  <!-- 마감된 레슨은 인기레슨리스트에서 제외된다. -->\r\n");
      out.write("		<div class=\"title\"> ");
      out.print(userAddr );
      out.write(" 인기레슨</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		");
		
		ArrayList<LessonDTO> pop_arr=null;
		
		if(m_id==null||m_id.equals("")||m_id.equals("admin")){
		pop_arr=ldao.lessonPopularList(pop_cp,pop_listSize);
		}else{
		pop_arr=ldao.lessonPopularList(mdto.getM_addr(),pop_cp,pop_listSize);
		}
		
		if(pop_arr==null||pop_arr.size()==0){
			
      out.write("\r\n");
      out.write("			<table class=\"lessonTable\" >\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">\r\n");
      out.write("					현재 등록된 레슨이 없습니다.\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			");

		}else{
			
      out.write("\r\n");
      out.write("			<table class=\"lessonTable\">\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				");

				if(pop_userGroup!=0){ //이전 화살표
				
      out.write("\r\n");
      out.write("				<a href=\"lessonList.jsp?pop_cp=");
      out.print((pop_userGroup-1)*pop_pageSize+pop_pageSize);
      out.write("\" class=\"joinbt\" >&lt;&lt;</a>\r\n");
      out.write("				");

				}else{
				
      out.write("\r\n");
      out.write("				<a href=\"lessonList.jsp?pop_cp=");
      out.print(pop_totalCnt);
      out.write("\" class=\"joinbt\">&lt;&lt;</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				");

				for(int i=0;i<pop_arr.size();i++){
				
      out.write("\r\n");
      out.write("				<td><a href=\"lessonContent.jsp?l_idx=");
      out.print(pop_arr.get(i).getL_idx());
      out.write("\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"enddate\">\r\n");
      out.write("						<div>");
      out.print(pop_arr.get(i).getL_enddate() );
      out.write("</div> <!-- 마감일 -->\r\n");
      out.write("						<div style=\"color:tomato; font-weight:bold; font-size:20px;\">D-");
      out.print(ldao.lessonDDay(pop_arr.get(i).getL_idx()) );
      out.write("</div></li>\r\n");
      out.write("					<li class=\"l_name\">");
      out.print(pop_arr.get(i).getL_name() );
      out.write("</li><br> <!-- 레슨명 -->\r\n");
      out.write("					<li ><label id=\"joinbtn4\">작성자</label>\r\n");
      out.write("					&nbsp;&nbsp;<span>");
      out.print(pop_arr.get(i).getM_name());
      out.write('(');
      out.print(pop_arr.get(i).getM_id() );
      out.write(")</span></li><br><!-- 작성자 문제 -->\r\n");
      out.write("					<li ><label id=\"joinbtn4\">한줄소개</label>\r\n");
      out.write("					&nbsp;&nbsp;<span>");
      out.print(pop_arr.get(i).getL_con().length() >= 25?
							pop_arr.get(i).getL_con().substring(0, 25)+".....":pop_arr.get(i).getL_con() );
      out.write("</span></li><br><br>\r\n");
      out.write("					<li class=\"l_people\"><label id=\"joinbtn4\">모집인원</label>\r\n");
      out.write("					<meter min=\"0\" max=\"");
      out.print(pop_arr.get(i).getL_people());
      out.write("\" value=\"");
      out.print(pop_arr.get(i).getM_idxcnt());
      out.write("\"></meter>\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;");
      out.print(pop_arr.get(i).getM_idxcnt() );
      out.write('/');
      out.print(pop_arr.get(i).getL_people());
      out.write("\r\n");
      out.write("					");
if( pop_arr.get(i).getL_people() ==  pop_arr.get(i).getM_idxcnt()+1){
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;<span style=\"position:absolute; font-size:16px; color:gray; font-weight:bold;\">딱 한자리 남았어요~</span >\r\n");
      out.write("					");

					}else if(pop_arr.get(i).getL_people() ==  pop_arr.get(i).getM_idxcnt()){
					
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;<span style=\"position:absolute; font-size:16px; color:gray; font-weight:bold;\">신청인원이<br>마감되었어요!</span >\r\n");
      out.write("					");
}else{
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;<span></span >\r\n");
      out.write("					");
} 
      out.write("</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				</a></td>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				<td>\r\n");
      out.write("				");

				if(pop_userGroup!=(pop_totalPage/pop_pageSize)-(pop_totalPage%pop_pageSize==0?1:0)){  //다음 화살표
				
      out.write("\r\n");
      out.write("				<a href=\"lessonList.jsp?pop_cp=");
      out.print((pop_userGroup+1)*pop_pageSize+1 );
      out.write("\" class=\"joinbt\">&gt;&gt;</a>\r\n");
      out.write("				");

				}else{
				
      out.write("\r\n");
      out.write("				<a href=\"lessonList.jsp?pop_cp=1\" class=\"joinbt\">&gt;&gt;</a>\r\n");
      out.write("				");

				}
				
      out.write("	\r\n");
      out.write("				</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br><br>\r\n");
      out.write("				");

		}
		
      out.write("\r\n");
      out.write("		<br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("	</article>\r\n");
      out.write("	\r\n");
      out.write("	<article id=\"searchBar\">\r\n");
      out.write("	<form name=\"lessonSearch\" action=\"lessonSearch.jsp\">\r\n");
      out.write("		<select name=\"searchKey\">\r\n");
      out.write("			<option value=\"l_name||l_con\">전체</option><!-- l_name컬럼과 l_name컬럼 2개를 불러올 수 있다. -->\r\n");
      out.write("			<option value=\"l_name\">레슨명</option>\r\n");
      out.write("			<option value=\"l_con\">레슨설명</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		");
if(m_id==null||m_id.equals("")){	
		}else{
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"m_addr\" value=\"");
      out.print(mdto.getM_addr());
      out.write("\">\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("		<input type=\"text\" name=\"searchValue\" size=\"30\">\r\n");
      out.write("		<input type=\"submit\" value=\"검색\" class=\"joinbt\">\r\n");
      out.write("	</form>\r\n");
      out.write("	</article>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<article>\r\n");
      out.write("		<div class=\"title\">");
      out.print(userAddr );
      out.write(" 전체레슨</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		");

		ArrayList<LessonDTO> arr=null;
		if(m_id==null||m_id.equals("")||m_id.equals("admin")){
			arr=ldao.lessonList(cp,listSize);
		}else{
			arr=ldao.lessonList(mdto.getM_addr(),cp,listSize);
		}
		if(arr==null||arr.size()==0){
			
      out.write("\r\n");
      out.write("			<table class=\"lessonTable\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">\r\n");
      out.write("					현재 등록된 레슨이 없습니다.\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			");

			
		}else{
		for(int i=0;i<arr.size();i++){
		
      out.write("\r\n");
      out.write("		<table class=\"lessonTable\" >\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><a href=\"lessonContent.jsp?l_idx=");
      out.print(arr.get(i).getL_idx());
      out.write("\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"enddate\">\r\n");
      out.write("					<div>");
      out.print(arr.get(i).getL_enddate() );
      out.write("</div> <!-- 마감일 -->\r\n");
      out.write("					<div style=\"color:tomato; font-weight:bold; font-size:20px;\">D-");
      out.print(ldao.lessonDDay(arr.get(i).getL_idx()) );
      out.write("</div></li>\r\n");
      out.write("					<li class=\"l_name\">");
      out.print(arr.get(i).getL_name() );
      out.write("</li><br>\r\n");
      out.write("					<li ><label id=\"joinbtn4\">작성자</label>\r\n");
      out.write("					&nbsp;&nbsp;<span>");
      out.print(arr.get(i).getM_name());
      out.write('(');
      out.print(arr.get(i).getM_id() );
      out.write(")</span></li><br><!-- 작성자 문제 -->\r\n");
      out.write("					<li ><label id=\"joinbtn4\">한줄소개</label>\r\n");
      out.write("					&nbsp;&nbsp;<span>");
      out.print(arr.get(i).getL_con().length()>=25?
					arr.get(i).getL_con().substring(0, 25)+"...":arr.get(i).getL_con() );
      out.write("</span></li><br><br>\r\n");
      out.write("					<li class=\"l_people\"><label id=\"joinbtn4\">모집인원</label>\r\n");
      out.write("					<meter  min=\"0\" max=\"");
      out.print(arr.get(i).getL_people());
      out.write("\" value=\"");
      out.print(arr.get(i).getM_idxcnt());
      out.write("\"></meter>	\r\n");
      out.write("					&nbsp;&nbsp;");
      out.print(arr.get(i).getM_idxcnt() );
      out.write('/');
      out.print(arr.get(i).getL_people());
      out.write("\r\n");
      out.write("					");
if( arr.get(i).getL_people() ==  arr.get(i).getM_idxcnt()+1){
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;<span style=\"position:absolute; font-size:16px; color:gray; font-weight:bold;\">딱 한자리 남았어요~</span >\r\n");
      out.write("					");

					}else if(arr.get(i).getL_people() ==  arr.get(i).getM_idxcnt()){
					
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;<span style=\"position:absolute; font-size:16px; color:gray; font-weight:bold;\">신청인원이<br>마감되었어요!</span >\r\n");
      out.write("					");
}else{
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;&nbsp;<span></span >\r\n");
      out.write("					");
} 
      out.write("</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				</a></td></tr></table>\r\n");
      out.write("		<br><br>\r\n");
      out.write("		\r\n");
      out.write("		");

			}
		}
		
      out.write("\r\n");
      out.write("		<div style=\"text-align: center;\">\r\n");
      out.write("		");

			if(userGroup!=0){ //이전 화살표
		
      out.write("\r\n");
      out.write("			<a href=\"lessonList.jsp?cp=");
      out.print((userGroup-1)*pageSize+pageSize);
      out.write("\"><img alt=\"/tomato/img/leftBt.png\" src=\"l버튼\"></a>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		");
     //시작페이지*5+1
			for(int i=userGroup*3+1;i<=userGroup*pageSize+pageSize;i++){  //페이지 만들기
		
      out.write("\r\n");
      out.write("			&nbsp;&nbsp;<a href=\"lessonList.jsp?cp=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>&nbsp;&nbsp;\r\n");
      out.write("		");
 //cp파라미터로 인위적으로 이동
				if(i==totalPage){
				break;
				}
			}
	 	
      out.write("\r\n");
      out.write("		");

			if(userGroup!=(totalPage/pageSize)-(totalPage%pageSize==0?1:0)){  //다음 화살표
		
      out.write("\r\n");
      out.write("			<a href=\"lessonList.jsp?cp=");
      out.print((userGroup+1)*pageSize+1 );
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("		");

			}
		
      out.write("	\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"text-align: right;\">\r\n");
      out.write("		<a href=\"lessonUpload.jsp\"><input type=\"button\" value=\"레슨 등록하기\" class=\"joinbt\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div>\r\n");
      out.write("고객문의&nbsp;&nbsp;ezen@gamil.com &nbsp;&nbsp;&nbsp;&nbsp;제휴문의&nbsp;&nbsp;ezen@naver.com\r\n");
      out.write("<br/>\r\n");
      out.write("지역광고&nbsp;&nbsp;ezen@gamil.com\r\n");
      out.write("<br/>\r\n");
      out.write("주소&nbsp;&nbsp;서울특별시 서대문구 신촌로 141 은하빌딩 1층 이젠아카데미 컴퓨터학원\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<div>Copyright &copy; Ezen & 3th. All Rights Reserved.</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
