/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-19 08:59:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lesson;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import tomato.lesson.*;
import tomato.lesson_re.*;

public final class lessonContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1633071175604L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1634624681575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("tomato.lesson");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("tomato.lesson_re");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      tomato.lesson.LessonDAO ldao = null;
      synchronized (session) {
        ldao = (tomato.lesson.LessonDAO) _jspx_page_context.getAttribute("ldao", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (ldao == null){
          ldao = new tomato.lesson.LessonDAO();
          _jspx_page_context.setAttribute("ldao", ldao, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      tomato.lesson_re.LessonReDAO lrdao = null;
      lrdao = (tomato.lesson_re.LessonReDAO) _jspx_page_context.getAttribute("lrdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (lrdao == null){
        lrdao = new tomato.lesson_re.LessonReDAO();
        _jspx_page_context.setAttribute("lrdao", lrdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

   String idx_s=request.getParameter("l_idx");
   if(idx_s==null||idx_s.equals("")){
      idx_s="0";
   }
   
   int l_idx=Integer.parseInt(idx_s);
   LessonDTO dto=ldao.lessonContent(l_idx);
   
   if(dto.getL_del()==1){
	   
      out.write("\r\n");
      out.write("	   <script>\r\n");
      out.write("	   window.alert('존재하지 않는 게시물입니다.');\r\n");
      out.write("	   window.history.back();\r\n");
      out.write("	   </script>\r\n");
      out.write("	   ");

   }
   else if(dto.getL_del()==1){
	   
      out.write("\r\n");
      out.write("	   <script>\r\n");
      out.write("	   window.alert('존재하지 않는 게시물입니다.');\r\n");
      out.write("	   window.history.back();\r\n");
      out.write("	   </script>\r\n");
      out.write("	   ");

	}


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script>\r\n");
      out.write("function reReWriteBox(l_r_idx){   \r\n");
      out.write("   var replyDom=document.getElementById(l_r_idx).nextElementSibling;\r\n");
      out.write("   var display=replyDom.style.display;\r\n");
      out.write("   \r\n");
      out.write("   if(display=='none'){\r\n");
      out.write("      replyDom.style.display='block';\r\n");
      out.write("   }else{\r\n");
      out.write("      replyDom.style.display='none';\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tomato/css/mainLayout.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("      background: #f5f4f0;\r\n");
      out.write("      font-family: 'Roboto';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3{\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   font-size: 40px;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("}\r\n");
      out.write("article{\r\n");
      out.write("   width: 750px;\r\n");
      out.write("   margin: 0px auto;\r\n");
      out.write("   padding:15px;\r\n");
      out.write("}\r\n");
      out.write(".joinbt{\r\n");
      out.write("   text-align: right;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".joinbt:hover{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".reply1{\r\n");
      out.write("   width: 650px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write(".reply1 ul{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".reply1 ul li{\r\n");
      out.write("   margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write(".reList{\r\n");
      out.write("   width: 650px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".reList ul li{\r\n");
      out.write("   margin: 15px 0;\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#btn1{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#btn1:hovertn1{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");

String m_id=(String)session.getAttribute("m_id");
String m_name=(String)session.getAttribute("m_name");
if(m_id==null){
   
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   <a href=\"/tomato/member/login.jsp\">로그인</a> | <a href=\"/tomato/member/join.jsp\">회원가입</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
 
}else{
      
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   ");

   if(m_id.equals("admin")){
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/admin/memberList_admin.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }else{
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/member/mypage.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }
   
      out.write("\r\n");
      out.write("   <a href=\"/tomato/member/logout.jsp\">로그아웃</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");

}

      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><h1><a href=\"/tomato/index.jsp\"><img src=\"/tomato/img/토마토_메인로고.png\" alt=\"메인로고\" height=\"50px\" width=\"250px\"></a></h1></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/sell/sell.jsp\">SELL</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/buy/buyList.jsp?col=s_idx&range=desc\">BUY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/lesson/lessonList.jsp\">LESSON</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/community/community.jsp\">COMMUNITY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/qna/qnaList.jsp\">Q&A</a></h2></li>\r\n");
      out.write("   <li>\r\n");
      out.write("		<form name=\"headerSearch\" action=\"/tomato/buy/headerBuySearch.jsp\" style=\"display: inline;\">\r\n");
      out.write("			<input type=\"text\" name=\"searchValue\" placeholder=\"상품을 검색하세요\">\r\n");
      out.write("			<input type=\"submit\" value=\"검색\" id=\"btn1\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<hr/>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');


int m_idx=ldao.selectMidx(m_id);

int reTotalCnt=lrdao.getReTotalCnt(l_idx);
/*레슨 댓글 리스트*/
int listSize=15;
int pageSize=5;
String cp_s=request.getParameter("cp");
if(cp_s==null||cp_s.equals("")){
   cp_s="1";
}
int cp=Integer.parseInt(cp_s);

int totalPage=(reTotalCnt/listSize)+1;
if(reTotalCnt%listSize==0)totalPage--;

int userGroup=cp/pageSize;
if(cp%pageSize==0)userGroup--;

      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("   <article>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <form name=\"lessonContent\" action=\"lessonJoin_ok.jsp\">\r\n");
      out.write("   <span style=\"font-size:40px;\">");
      out.print(dto.getL_name() );
      out.write("</span>\r\n");
      out.write("   <span style=\"float: right;\">\r\n");
      out.write("      ");

      if(m_idx==dto.getM_idx()){ //본문과 접속자가 일치 || 관리자가 접속
      
      out.write("\r\n");
      out.write("         <input type=\"button\" value=\"삭제하기\"  onclick=\"location.href='lessonDel_ok.jsp?l_idx=");
      out.print(dto.getL_idx());
      out.write("&l_name=");
      out.print(dto.getL_name());
      out.write("'\" class=\"joinbt\">&nbsp;\r\n");
      out.write("         <input type=\"button\" value=\"수정하기\" onclick=\"location.href='lessonUpdate.jsp?l_idx=");
      out.print(dto.getL_idx());
      out.write("'\" class=\"joinbt\">\r\n");
      out.write("      ");

      }else if(m_idx==1){
      
      out.write("\r\n");
      out.write("         <input type=\"button\" value=\"삭제하기\"  onclick=\"location.href='lessonDel_ok.jsp?l_idx=");
      out.print(dto.getL_idx());
      out.write("&l_name=");
      out.print(dto.getL_name());
      out.write("'\" class=\"joinbt\">\r\n");
      out.write("      ");

      }else{
      
      out.write("\r\n");
      out.write("         <input type=\"hidden\" name=\"l_idx\" value=\"");
      out.print(dto.getL_idx());
      out.write("\">\r\n");
      out.write("         <input type=\"hidden\" name=\"lm_idx\" value=\"");
      out.print(dto.getM_idx() );
      out.write("\">\r\n");
      out.write("         <input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx);
      out.write("\">\r\n");
      out.write("         ");
if(dto.getL_people() ==  dto.getM_idxcnt()){ 
      out.write("\r\n");
      out.write("            <input type=\"button\" value=\"신청인원마감\" class=\"joinbt\">\r\n");
      out.write("         ");
}else{ 
      out.write("\r\n");
      out.write("            <input type=\"submit\" value=\"신청하기\" class=\"joinbt\">\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("         &nbsp;<input type=\"button\" value=\"신청취소\" class=\"joinbt\" onclick=\"location.href='lessonJoinCancle_ok.jsp?l_idx=");
      out.print(dto.getL_idx());
      out.write("&lm_idx=");
      out.print(dto.getM_idx());
      out.write("&m_idx=");
      out.print(m_idx );
      out.write("'\">\r\n");
      out.write("      ");

      }
      
      out.write("\r\n");
      out.write("      </span>\r\n");
      out.write("      <hr>\r\n");
      out.write("         <p align=\"left\" style=\"word-break:break-all; height:300px;\">         \r\n");
      out.write("            설명:&nbsp;");
if(dto.getL_con()!=null){ 
      out.write("       <!-- 20자 이상 쓰게 유효성7 -->\r\n");
      out.write("            ");
      out.print(dto.getL_con().replaceAll("\n", "<br>") );
      out.write("\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("         </p>\r\n");
      out.write("         <hr>\r\n");
      out.write("   </form>\r\n");
      out.write("   </article>\r\n");
      out.write("   <article>\r\n");
      out.write("   ");
ArrayList<LessonReDTO> arr=lrdao.lessonReList(l_idx,cp,listSize);
      out.write("\r\n");
      out.write("   <!-- 댓글 입력창 -->\r\n");
      out.write("      <form name=\"lessonReWrite\" action=\"lessonReWrite_ok.jsp\">\r\n");
      out.write("      <div class=\"reply1\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("               ");

               if(arr==null||arr.size()==0){
               
      out.write("\r\n");
      out.write("                  <label style=\"font-weight: bold;\">댓글</label>&nbsp;<label style=\"font-weight:bold;color:teal;\">0</label>\r\n");
      out.write("               ");

               }else{
               
      out.write("\r\n");
      out.write("                  <label style=\"font-weight: bold;\">댓글</label>&nbsp;<label style=\"font-weight:bold;color:teal;\">");
      out.print(reTotalCnt );
      out.write("</label>\r\n");
      out.write("               ");

               }
               
      out.write("\r\n");
      out.write("            </li>\r\n");
      out.write("               ");

               String msg;
               String readStatus;
               if(m_idx==0){
                  msg="댓글은 회원만 작성 가능합니다.";
                  readStatus="readonly";
               }else{
                  msg="댓글을 입력하세요.";
                  readStatus="";
               }
               
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("               <textarea name=\"l_r_con\" placeholder=\"");
      out.print(msg );
      out.write("\" cols=\"80\" rows=\"4\" ");
      out.print(readStatus );
      out.write("></textarea>\r\n");
      out.write("               <input type=\"hidden\" name=\"l_idx\" value=\"");
      out.print(l_idx );
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx );
      out.write("\">\r\n");
      out.write("               <input type=\"submit\" value=\"입력하기\" class=\"joinbt\" >\r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </form>\r\n");
      out.write("   <hr>\r\n");
      out.write("   <ul>\r\n");
      out.write("      ");
 if(arr==null||arr.size()==0){
      out.write("\r\n");
      out.write("         <li>등록된 댓글이 없습니다.</li>\r\n");
      out.write("      ");
}else{
         for(int i=0;i<arr.size();i++){
      
      out.write("\r\n");
      out.write("   <br>\r\n");
      out.write("      <li id=\"");
      out.print(arr.get(i).getL_r_idx());
      out.write("\">\r\n");
      out.write("      ");

      for(int k=0;k<arr.get(i).getL_r_lev();k++){
      out.println("&nbsp;&nbsp;");
      }
      
      out.write("\r\n");
      out.write("         <span style=\"font-weight: bold; width: 120px;\">");
      out.print(arr.get(i).getM_name());
      out.write('(');
      out.print(arr.get(i).getM_id() );
      out.write(")</span>&nbsp;&nbsp;\r\n");
      out.write("         <span style=\"font-size:13px;\">");
      out.print(arr.get(i).getL_r_joindate() );
      out.write("</span>\r\n");
      out.write("         <span><input type=\"button\" value=\"답변\" onclick=\"reReWriteBox('");
      out.print(arr.get(i).getL_r_idx());
      out.write("');\" \r\n");
      out.write("            style=\"border:0px; color: tomato;font-weight:bold; background-color: white;float:right;\"></span>\r\n");
      out.write("      ");
 if(m_idx==arr.get(i).getM_idx()||m_idx==1){
      out.write("\r\n");
      out.write("         <span><a href=\"lessonReDel_ok.jsp?l_r_idx=");
      out.print(arr.get(i).getL_r_idx());
      out.write("&l_idx=");
      out.print(l_idx);
      out.write("\">\r\n");
      out.write("            <input type=\"button\" value=\"삭제\" style=\"border:0px; color: tomato;font-weight:bold; background-color: white;float:right;\" ></a></span>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("         <span style=\"word-break:break-all;\">");
      out.print(arr.get(i).getL_r_con().replaceAll("\n", "<br>") );
      out.write("</span>\r\n");
      out.write("      </li>\r\n");
      out.write("   <!-- 대댓글입력창 -->\r\n");
      out.write("      <li class=\"replyDom\" style=\"display:none;\">\r\n");
      out.write("         <form name=\"lessonReReWrite\" action=\"lessonReReWrite_ok.jsp\">\r\n");
      out.write("            <textarea name=\"l_r_con\" placeholder=\"");
      out.print(msg );
      out.write("\" cols=\"80\" rows=\"4\" ");
      out.print(readStatus );
      out.write("></textarea>\r\n");
      out.write("            <input type=\"hidden\" name=\"l_idx\" value=\"");
      out.print(l_idx );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"l_r_ref\" value=\"");
      out.print(arr.get(i).getL_r_ref() );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"l_r_lev\" value=\"");
      out.print(arr.get(i).getL_r_lev() );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"l_r_sunbun\" value=\"");
      out.print(arr.get(i).getL_r_sunbun() );
      out.write("\">\r\n");
      out.write("            <input type=\"submit\" value=\"입력하기\" class=\"joinbt\">\r\n");
      out.write("         </form>\r\n");
      out.write("      </li>\r\n");
      out.write("         ");

         }
      }
      
      out.write("\r\n");
      out.write("   </ul>\r\n");
      out.write("      \r\n");
      out.write("      <div style=\"text-align: center;\">\r\n");
      out.write("      ");

         if(userGroup!=0){ //이전 화살표
      
      out.write("\r\n");
      out.write("         <a href=\"lessonContent.jsp?l_idx=");
      out.print(l_idx );
      out.write("&cp=");
      out.print((userGroup-1)*pageSize+pageSize);
      out.write("\">&lt;&lt;</a>\r\n");
      out.write("      ");

         }
      
      out.write("\r\n");
      out.write("         ");

         for(int k=userGroup*5+1;k<=userGroup*pageSize+pageSize;k++){
         
      out.write("\r\n");
      out.write("         &nbsp;&nbsp;<a href=\"lessonContent.jsp?l_idx=");
      out.print(l_idx );
      out.write("&cp=");
      out.print(k);
      out.write('"');
      out.write('>');
      out.print(k);
      out.write("</a>&nbsp;&nbsp;\r\n");
      out.write("         ");
   
         if(k==totalPage){
            break;
            }
         }
         
      out.write("\r\n");
      out.write("         ");

         if(userGroup!=(totalPage/pageSize)-(totalPage%pageSize==0?1:0)){  //다음 화살표
      
      out.write("\r\n");
      out.write("         <a href=\"lessonContent.jsp?l_idx=");
      out.print(l_idx );
      out.write("&cp=");
      out.print((userGroup+1)*pageSize+1 );
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("      ");

         }
      
      out.write("   \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("   </article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div>\r\n");
      out.write("고객문의&nbsp;&nbsp;ezen@gamil.com &nbsp;&nbsp;&nbsp;&nbsp;제휴문의&nbsp;&nbsp;ezen@naver.com\r\n");
      out.write("<br/>\r\n");
      out.write("지역광고&nbsp;&nbsp;ezen@gamil.com\r\n");
      out.write("<br/>\r\n");
      out.write("주소&nbsp;&nbsp;서울특별시 서대문구 신촌로 141 은하빌딩 1층 이젠아카데미 컴퓨터학원\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<div>Copyright &copy; Ezen & 3th. All Rights Reserved.</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
