/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-20 02:09:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.buy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import tomato.sell.*;
import tomato.sell_re.*;
import tomato.member.*;

public final class buyContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1633071175604L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1634624681575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("tomato.member");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("tomato.sell_re");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("tomato.sell");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      tomato.sell.SellDAO sdao = null;
      synchronized (session) {
        sdao = (tomato.sell.SellDAO) _jspx_page_context.getAttribute("sdao", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sdao == null){
          sdao = new tomato.sell.SellDAO();
          _jspx_page_context.setAttribute("sdao", sdao, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      tomato.sell_re.SellReDAO srdao = null;
      srdao = (tomato.sell_re.SellReDAO) _jspx_page_context.getAttribute("srdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (srdao == null){
        srdao = new tomato.sell_re.SellReDAO();
        _jspx_page_context.setAttribute("srdao", srdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      tomato.member.MemberDAO mdao = null;
      mdao = (tomato.member.MemberDAO) _jspx_page_context.getAttribute("mdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdao == null){
        mdao = new tomato.member.MemberDAO();
        _jspx_page_context.setAttribute("mdao", mdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      tomato.buy.BuyDAO bdao = null;
      bdao = (tomato.buy.BuyDAO) _jspx_page_context.getAttribute("bdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bdao == null){
        bdao = new tomato.buy.BuyDAO();
        _jspx_page_context.setAttribute("bdao", bdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String s_idx_s=request.getParameter("s_idx");
if(s_idx_s==null||s_idx_s.equals("")){
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.alert('존재하지 않는 게시물입니다.');\r\n");
      out.write("	location.href='buyList.jsp?col=s_idx&range=desc';\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	return;
}
int s_idx=Integer.parseInt(s_idx_s);
SellDTO dto=sdao.getSellContent(s_idx);
if(dto==null){
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.alert('존재하지 않는 게시물입니다.');\r\n");
      out.write("	location.href='buyList.jsp?col=s_idx&range=desc';\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	return;
}else if(dto.getS_del()==1){
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.alert('존재하지 않는 게시물입니다.');\r\n");
      out.write("	window.history.back();\r\n");
      out.write("	</script>\r\n");
      out.write("	");

}

String imgPath=dto.getS_port();
int del=dto.getS_del();
boolean imgContain=imgPath.contains(",");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tomato/css/mainLayout.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("   background: #f5f4f0;\r\n");
      out.write("   font-family: 'Roboto';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sell_img{\r\n");
      out.write("   width: 700px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("#sell_img ul{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   display: inline;\r\n");
      out.write("   margin-top: 50px;\r\n");
      out.write("   float: left;\r\n");
      out.write("}\r\n");
      out.write("#sell_img ul li{\r\n");
      out.write("   margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("#sell_con{\r\n");
      out.write("   float: left;\r\n");
      out.write("   margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("#sell_con ul{\r\n");
      out.write("   float: left;\r\n");
      out.write("   list-style:none;\r\n");
      out.write("   display: inline;\r\n");
      out.write("}\r\n");
      out.write("#sell_con h3{\r\n");
      out.write("   font-size: 30px;\r\n");
      out.write("   color: darkgray;\r\n");
      out.write("}\r\n");
      out.write("#sell_re{\r\n");
      out.write("   clear: both;\r\n");
      out.write("}\r\n");
      out.write("#sell_re hr{\r\n");
      out.write("   border:0;\r\n");
      out.write("   height:1px;\r\n");
      out.write("   background:#c2c2c2;\r\n");
      out.write("   align: center;\r\n");
      out.write("   width: 650px;\r\n");
      out.write("}\r\n");
      out.write(".reply1{\r\n");
      out.write("   width: 650px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write(".reply1 ul{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".reply1 ul li{\r\n");
      out.write("   margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write(".reList{\r\n");
      out.write("   width: 650px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write(".reList ul{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write(".reList ul li{\r\n");
      out.write("   margin: 15px 0;\r\n");
      out.write("}\r\n");
      out.write("#pagingArea {\r\n");
      out.write("   width: 650px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   text-align:center;\r\n");
      out.write("}\r\n");
      out.write("#pagingArea ul{\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write("#pagingArea ul li{\r\n");
      out.write("   margin: 15px 0;\r\n");
      out.write("}\r\n");
      out.write(".plusBtn{\r\n");
      out.write("   height:80px;\r\n");
      out.write("   width:80px;\r\n");
      out.write("   backgound-color:gray;\r\n");
      out.write("   color:darkgray;\r\n");
      out.write("   font-weight:bold;\r\n");
      out.write("   font-size:40px;\r\n");
      out.write("   border:0px;\r\n");
      out.write("}\r\n");
      out.write(".plusDel{\r\n");
      out.write("   height:25px;\r\n");
      out.write("   width:25px;\r\n");
      out.write("   float:left;\r\n");
      out.write("   visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write(".updateBtn{\r\n");
      out.write("   border:0px;\r\n");
      out.write("   background-color:white;\r\n");
      out.write("   color:teal;\r\n");
      out.write("   font-weight:bold;\r\n");
      out.write("   font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("#pagingArea a{\r\n");
      out.write("   text-decoration:none;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputbtn{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write(".inputbtn:hover{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#joinbtn1{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#joinbtn1:hover{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function viewComment(reWrite){\r\n");
      out.write("	if(document.getElementById(reWrite).style.display==\"none\"){\r\n");
      out.write("		document.getElementById(reWrite).style.display=\"block\";\r\n");
      out.write("	}else if(document.getElementById(reWrite).style.display=\"block\"){\r\n");
      out.write("		document.getElementById(reWrite).style.display=\"none\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("function changeMainImg(getImgPath){\r\n");
      out.write("	document.getElementById(\"mainImg\").src=\"\"+getImgPath+\"\";\r\n");
      out.write("}\r\n");
      out.write("function plusImgPopup(){\r\n");
      out.write("	window.open('/tomato/sell/sellImgUpload.jsp', 'fileUpload', 'width=350, height=250');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#btn1{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#btn1:hovertn1{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");

String m_id=(String)session.getAttribute("m_id");
String m_name=(String)session.getAttribute("m_name");
if(m_id==null){
   
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   <a href=\"/tomato/member/login.jsp\">로그인</a> | <a href=\"/tomato/member/join.jsp\">회원가입</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
 
}else{
      
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   ");

   if(m_id.equals("admin")){
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/admin/memberList_admin.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }else{
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/member/mypage.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }
   
      out.write("\r\n");
      out.write("   <a href=\"/tomato/member/logout.jsp\">로그아웃</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");

}

      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><h1><a href=\"/tomato/index.jsp\"><img src=\"/tomato/img/토마토_메인로고.png\" alt=\"메인로고\" height=\"50px\" width=\"250px\"></a></h1></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/sell/sell.jsp\">SELL</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/buy/buyList.jsp?col=s_idx&range=desc\">BUY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/lesson/lessonList.jsp\">LESSON</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/community/community.jsp\">COMMUNITY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/qna/qnaList.jsp\">Q&A</a></h2></li>\r\n");
      out.write("   <li>\r\n");
      out.write("		<form name=\"headerSearch\" action=\"/tomato/buy/headerBuySearch.jsp\" style=\"display: inline;\">\r\n");
      out.write("			<input type=\"text\" name=\"searchValue\" placeholder=\"상품을 검색하세요\">\r\n");
      out.write("			<input type=\"submit\" value=\"검색\" id=\"btn1\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<hr/>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

int m_idx;
m_id=(String)session.getAttribute("m_id");
if(m_id==null||m_id.equals("")){
	m_idx=0;
}else{
	m_idx=mdao.selectMidx(m_id);
}
sdao.setCrpath("/"+m_id+"/"+s_idx);
sdao.setUserid("/"+m_id+"/"+s_idx);
sdao.setSellIdx(dto.getS_idx());

      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<!-- 제품 이미지----------- -->\r\n");
      out.write("	<article id=\"sell_img\">\r\n");
      out.write("	");

	//이미지 하나
	String plusImgViewOp=m_idx!=dto.getM_idx()?"hidden":"";
	String delImgViewOp="";
	if(m_idx!=dto.getM_idx()&&m_idx!=1){
		delImgViewOp="hidden";
	}
	if(!imgContain){
		if(imgPath.equals("\\tomato\\sell\\upload\\admin\\noImage.png")){
			
      out.write("\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("				<img src=\"/tomato/img/deleteImage.png\" class=\"plusDel\">\r\n");
      out.write("	 			<img src=\"");
      out.print(imgPath);
      out.write("\" alt=\"판매상품 이미지\" height=\"80\" width=\"80\">\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("				\r\n");
      out.write("					<img src=\"/tomato/img/deleteImage.png\" class=\"plusDel\">\r\n");
      out.write("					<input type=\"button\" value=\"+\" class=\"plusBtn\" style=\"visibility: ");
      out.print(plusImgViewOp);
      out.write(";\"\r\n");
      out.write("					onclick=\"plusImgPopup();\">\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<img src=\"");
      out.print(imgPath );
      out.write("\" alt=\"판매상품 대표이미지\" height=\"450\" width=\"450\"\r\n");
      out.write("		style=\"margin:50px;display:inline;\">\r\n");
      out.write("			");

		}else{
		
      out.write("\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>\r\n");
      out.write("			<img src=\"/tomato/img/deleteImage.png\" class=\"plusDel\">\r\n");
      out.write(" 			<img src=\"");
      out.print(imgPath);
      out.write("\" alt=\"판매상품 이미지\" height=\"80\" width=\"80\" >\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<img src=\"/tomato/img/deleteImage.png\" class=\"plusDel\">\r\n");
      out.write("				<input type=\"button\" value=\"+\" class=\"plusBtn\" style=\"visibility: ");
      out.print(plusImgViewOp);
      out.write(";\"\r\n");
      out.write("				onclick=\"plusImgPopup();\">\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<img src=\"");
      out.print(imgPath );
      out.write("\" alt=\"판매상품 대표이미지\" height=\"450\" width=\"450\"\r\n");
      out.write("		style=\"margin:50px;display:inline;\">\r\n");
      out.write("		");

		}
		//이미지 하나 이상
	}else{
		String imgPaths[]=imgPath.split(", ");
		out.println("<ul>");
		int remainImg=5-imgPaths.length;
		for(int i=0;i<imgPaths.length;i++){
			String filePort=sdao.USERS_HOME+"/"+m_id+"/"+dto.getS_idx();
			
      out.write("\r\n");
      out.write("			<form name=\"sele_imgForm\" action=\"deleteSellImg.jsp\" method=\"post\">\r\n");
      out.write("				<li>\r\n");
      out.write("				<input type=\"hidden\" name=\"delImgPort\" value=\"");
      out.print(sdao.DELETE_IMG_ROOT+imgPaths[i]);
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"filePort\" value=\"");
      out.print(filePort );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"s_idx\" value=\"");
      out.print(dto.getS_idx() );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"m_id\" value=\"");
      out.print(m_id );
      out.write("\">\r\n");
      out.write("				<input type=\"image\" src=\"/tomato/img/deleteImage.png\" alt=\"판매상품 삭제\"\r\n");
      out.write("				style=\"height:25px;width:25px;float:left;visibility:");
      out.print(delImgViewOp);
      out.write(";\">\r\n");
      out.write("				<img src=\"");
      out.print(imgPaths[i] );
      out.write("\" alt=\"판매상품 이미지");
      out.print(i+1 );
      out.write("\" height=\"80\" width=\"80\" \r\n");
      out.write("				onclick=\"changeMainImg('");
      out.print(imgPaths[i]);
      out.write("')\">\r\n");
      out.write("				</li>\r\n");
      out.write("			</form>\r\n");
      out.write("			");

		}
		if(remainImg>0){
			
      out.write("\r\n");
      out.write("			<li>\r\n");
      out.write("				<img src=\"/tomato/img/deleteImage.png\" class=\"plusDel\">\r\n");
      out.write("				<input type=\"button\" value=\"+\" class=\"plusBtn\" style=\"visibility: ");
      out.print(plusImgViewOp);
      out.write(";\"\r\n");
      out.write("				onclick=\"plusImgPopup();\">\r\n");
      out.write("			</li>\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("		<img src=\"");
      out.print(imgPaths[0] );
      out.write("\" alt=\"판매상품 대표이미지\" height=\"450\" width=\"450\"\r\n");
      out.write("		style=\"margin:50px;\" id=\"mainImg\">\r\n");
      out.write("		");

	}
	
      out.write("\r\n");
      out.write("	</article>\r\n");
      out.write("	<!-- ---------제품 정보(이름, 섦명, 가격, 장바구니) -->\r\n");
      out.write("	<article id=\"sell_con\">\r\n");
      out.write("		<form name=\"sell_con\" method=\"post\" action=\"buyItem_ok.jsp\">\r\n");
      out.write("		<input type=\"hidden\" name=\"s_idx\" value=\"");
      out.print(s_idx);
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx);
      out.write("\">\r\n");
      out.write("			<ul><li>\r\n");
      out.write("				<label style=\"font-size:16px;font-weight:bold;color:teal;\">[");
      out.print(dto.getS_cate() );
      out.write("]</label>\r\n");
      out.write("				");

				String itemUpdateOp;
				if(m_idx!=dto.getM_idx()){
					itemUpdateOp="none";
				}else if(dto.getS_del()==1){
					itemUpdateOp="none";
				}else{
					itemUpdateOp="inline";
				}
				
				String itemDelOp;
				if((m_idx==1||(m_idx==dto.getM_idx())&&dto.getS_del()==0)){
					itemDelOp="inline";
				}else{
					itemDelOp="none";
				}
				
      out.write("\r\n");
      out.write("				<div id=\"updateItem\" style=\"float:right;\">\r\n");
      out.write("				<input type=\"submit\" formaction=\"/tomato/sell/sell_update.jsp\" value=\"수정\" class=\"updateBtn\" style=\"display:");
      out.print(itemUpdateOp );
      out.write(";\">\r\n");
      out.write("				<input type=\"submit\" formaction=\"/tomato/sell/sell_delete.jsp\" value=\"삭제\" class=\"updateBtn\" style=\"display:");
      out.print(itemDelOp );
      out.write(";\">\r\n");
      out.write("				</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("				<h3>");
      out.print(dto.getS_name() );
      out.write("</h3>\r\n");
      out.write("				</li>\r\n");
      out.write("				<hr style=\"width:30px;border:0;background:#c2c2c2;width:450px;height:1px;\"/>\r\n");
      out.write("				<li><p style=\"line-height:2;font-size: 18px;color: dimgray;font-weight:normal;width:450px;height:180px;\">\r\n");
      out.write("				");
      out.print(dto.getS_con().replace("\n", "<br>") );
      out.write("</p></li>\r\n");
      out.write("				<li><label style=\"color: tomato;font-weight:bold;font-size:28px;word-break:break-all;\">\r\n");
      out.write("				&nbsp;");
      out.print(dto.getS_price() );
      out.write("</label><label style=\"color: dimgray;\">&nbsp;&nbsp;원</label></li>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<br/>\r\n");
      out.write("				");

				int result=bdao.getbuyY_N(s_idx, m_idx);
				if(m_idx==0||dto.getS_sellok()==1||dto.getS_del()==1||m_idx==1||m_idx==dto.getM_idx()){
					
      out.write("\r\n");
      out.write("					<li style=\"float:right;\">\r\n");
      out.write("					<label style=\"color: tomato;font-size:25px;\">&nbsp;&nbsp;");
      out.print(dto.getS_count() );
      out.write("</label></li>\r\n");
      out.write("					");

				}else if(result==0){
					
      out.write("\r\n");
      out.write("					<li style=\"float:right;\">\r\n");
      out.write("					<input type=\"image\" src=\"/tomato/img/cart_icon.png\" alt=\"상품 장바구니 이미지\" style=\"height:30px;width:30px;\">\r\n");
      out.write("					<label style=\"color: tomato;font-size:25px;\">&nbsp;&nbsp;");
      out.print(dto.getS_count() );
      out.write("</label></li>\r\n");
      out.write("					");

				}else if(result==1){
					
      out.write("\r\n");
      out.write("					<li style=\"float:right;\">\r\n");
      out.write("					<input type=\"image\" src=\"/tomato/img/cart_icon_2.png\" alt=\"상품 장바구니 이미지\" \r\n");
      out.write("					formaction=\"deletebuy_ok.jsp\" style=\"height:30px;width:30px;\">\r\n");
      out.write("					<label style=\"color: tomato;font-size:25px;\">&nbsp;&nbsp;");
      out.print(dto.getS_count() );
      out.write("</label></li>\r\n");
      out.write("					");

				}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</form>\r\n");
      out.write("	</article>\r\n");
      out.write("	<br/>\r\n");
      out.write("	<br/>\r\n");
      out.write("	<!-- -------------------------- -->\r\n");
      out.write("	<article id=\"sell_re\">\r\n");
      out.write("	");

	int totalCnt=srdao.getTotalCnt(s_idx);
	int listSize=20;
	int pageSize=10;
	
	String currentPage_s=request.getParameter("currentPage");
	if(currentPage_s==null||currentPage_s.equals("")){
		currentPage_s="1";
	}
	int currentPage=Integer.parseInt(currentPage_s);
	
	int totalPage=totalCnt/listSize+1;
	if(totalCnt%listSize==0)totalPage--;

	int userGroup=currentPage/pageSize;
	if(currentPage%pageSize==0)userGroup--;
	//댓글 배열 저장
	ArrayList<SellReDTO> arr=srdao.sellReList(s_idx, currentPage, listSize);
	//댓글 입력 창(삭제된 )
	
      out.write("\r\n");
      out.write("	<form name=\"buyContent_re\" method=\"post\" action=\"write_ok.jsp\">\r\n");
      out.write("	<br/>\r\n");
      out.write("	<br/>\r\n");
      out.write("	<input type=\"hidden\" name=\"s_idx\" value=\"");
      out.print(s_idx );
      out.write("\">\r\n");
      out.write("	<input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx );
      out.write("\">\r\n");
      out.write("	<div class=\"reply1\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>\r\n");
      out.write("			");

			if(arr!=null&&arr.size()!=0){
				
      out.write("\r\n");
      out.write("				<label style=\"font-weight: bold;\">댓글</label>&nbsp;<label style=\"font-weight:bold;color:teal;\">");
      out.print(totalCnt );
      out.write("</label>\r\n");
      out.write("				");

			}else{
				
      out.write("\r\n");
      out.write("				<label style=\"font-weight: bold;\">댓글</label>&nbsp;<label style=\"font-weight:bold;color:teal;\">0</label>\r\n");
      out.write("				");

			}
			
      out.write("\r\n");
      out.write("			</li>\r\n");
      out.write("			");

			//회원이 아닐 때, 삭제된 게시물일 때 댓글 입력 불가, 
			//회원인 경우에만 댓글 입력 가능.
			String msg;
			String readOp;
			String login;
			if(dto.getS_del()==1){
				msg="삭제된 게시물입니다.";
				readOp="readonly";
				login="none";
			}else if(m_idx==0){
				msg="댓글은 회원만 작성 가능합니다.";
				readOp="readonly";
				login="none";
			}else{
				msg="댓글을 입력하세요.";
				readOp="";
				login="block";
			}
			
      out.write("\r\n");
      out.write("			<li>\r\n");
      out.write("				<textarea name=\"s_r_con\" placeholder=\"");
      out.print(msg );
      out.write("\" cols=\"80\" rows=\"4\" ");
      out.print(readOp );
      out.write("></textarea>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<input type=\"submit\" value=\"입력하기\" style=\"display:");
      out.print(login);
      out.write(";\">\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<hr/>\r\n");
      out.write("	<!-- ------댓글 목록 -->\r\n");
      out.write("		<div class=\"reList\">\r\n");
      out.write("		");

		//댓글이 있을 때 
		if(arr!=null&&arr.size()!=0){
			for(int i=0;i<arr.size();i++){
				
      out.write("\r\n");
      out.write("				<form name=\"replyinput");
      out.print(i);
      out.write("\"  method=\"post\" action=\"reWrite_ok.jsp\">\r\n");
      out.write("				<input type=\"hidden\" name=\"s_r_idx\" value=\"");
      out.print(arr.get(i).getS_r_idx());
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"s_idx\" value=\"");
      out.print(s_idx );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"s_r_ref\" value=\"");
      out.print(arr.get(i).getS_r_ref() );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"s_r_lev\" value=\"");
      out.print(arr.get(i).getS_r_lev() );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"s_r_sunbun\" value=\"");
      out.print(arr.get(i).getS_r_sunbun() );
      out.write("\">\r\n");
      out.write("				<div id=\"reList");
      out.print(i );
      out.write("\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>\r\n");
      out.write("						");

						for(int k=0;k<arr.get(i).getS_r_lev();k++){
						out.println("&nbsp;&nbsp;");
						}
						
						String replyId=srdao.getMemberId(arr.get(i).getM_idx());
						if(arr.get(i).getM_idx()==dto.getM_idx()){
							replyId="[판매자] "+replyId;
						}
						
      out.write("\r\n");
      out.write("							<label style=\"font-weight: bold; width: 120px;\">");
      out.print(replyId );
      out.write("</label>\r\n");
      out.write("							<label style=\"font-size:13px;\">");
      out.print(arr.get(i).getS_r_joindate() );
      out.write("</label>\r\n");
      out.write("							");

							int delstatus=arr.get(i).getS_r_del();
							String delOp;
							if(arr.get(i).getM_idx()==m_idx&&(delstatus==0&&dto.getS_del()==0)){
								delOp="block";
							}else if(m_idx==1&&(delstatus==0&&dto.getS_del()==0)){
								delOp="block";
							}else{
								delOp="none";
							}
							
      out.write("\r\n");
      out.write("							<input type=\"submit\" value=\"삭제\" \r\n");
      out.write("							style=\"border:0px; color: tomato;font-weight:bold; background-color: white;float:right;display:");
      out.print(delOp );
      out.write(";\"\r\n");
      out.write("							formaction=\"/tomato/buy/delete_ok.jsp\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						");

						for(int k=0;k<arr.get(i).getS_r_lev();k++){
						out.println("&nbsp;&nbsp;");
						}
						//댓글 쓴 사람, 관리자, 판매자만 해당 댓글 보기 가능
						String replyConView;
						int reWriter=srdao.getReWriter(arr.get(i).getS_r_ref(), arr.get(i).getS_idx());
						if(m_idx==arr.get(i).getM_idx()||m_idx==1||m_idx==dto.getM_idx()||m_idx==reWriter||dto.getM_idx()==reWriter){
							replyConView=arr.get(i).getS_r_con().replaceAll("\n", "<br>");
						}else{
							replyConView="판매자와 작성자만 댓글을 볼 수 있습니다.";
						}
						String reWriteIcon;
						if(m_idx==arr.get(i).getM_idx()||m_idx==1||m_idx==dto.getM_idx()||m_idx==reWriter){
							reWriteIcon="block";
						}else{
							reWriteIcon="none";
						}
						
      out.write("\r\n");
      out.write("							<label style=\"word-break:break-all;\">");
      out.print(replyConView );
      out.write("</label>\r\n");
      out.write("						</li>\r\n");
      out.write("						<!-- ------대댓글 입력창 -->\r\n");
      out.write("						<li style=\"display:");
      out.print(reWriteIcon);
      out.write(";\">\r\n");
      out.write("						");

						String replyWrite="reply"+i+"Write";
						for(int k=0;k<arr.get(i).getS_r_lev();k++){
						out.println("&nbsp;&nbsp;");
						}
						
      out.write("\r\n");
      out.write("						<img src=\"/tomato/img/comment icon.png\" style=\"height:30px;width:30px;\" onclick=\"viewComment('");
      out.print(replyWrite);
      out.write("');\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<!-- -------댓글 리스트 -->\r\n");
      out.write("					</ul>\r\n");
      out.write("					<div id=\"reply");
      out.print(i);
      out.write("Write\" style=\"display:none;\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("								<textarea name=\"s_r_con\" placeholder=\"");
      out.print(msg );
      out.write("\" cols=\"80\" rows=\"4\" ");
      out.print(readOp );
      out.write("></textarea>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<input type=\"submit\" value=\"입력하기\" id=\"joinbtn1\" style=\"display:");
      out.print(login);
      out.write(";\">\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<hr/>\r\n");
      out.write("				</form>\r\n");
      out.write("				");

			}
		}
		
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"pagingArea\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					");

					if(userGroup!=0){
						
      out.write("\r\n");
      out.write("						<a href=\"buyContent.jsp?currentPage=1&s_idx=");
      out.print(s_idx );
      out.write("\">&lt;&lt;</a>\r\n");
      out.write("						<a href=\"buyContent.jsp?currentPage=");
      out.print((userGroup-1)*pageSize+pageSize );
      out.write("&s_idx=");
      out.print(s_idx );
      out.write("\">&lt;</a>\r\n");
      out.write("						");

					}
					
      out.write("\r\n");
      out.write("					");
 
					for(int i=userGroup*pageSize+1;i<=userGroup*pageSize+pageSize;i++){
						
      out.write("&nbsp;&nbsp;<a href=\"buyContent.jsp?currentPage=");
      out.print(i);
      out.write("&s_idx=");
      out.print(s_idx );
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</a>&nbsp;&nbsp;");

						if(i==totalPage){
							break;
						}
					}
					
      out.write("\r\n");
      out.write("					");

					if(userGroup!=(totalPage/pageSize)-(totalPage%pageSize==0?1:0)){
						
      out.write("\r\n");
      out.write("						<a href=\"buyContent.jsp?currentPage=");
      out.print((userGroup+1)*pageSize+1 );
      out.write("&s_idx=");
      out.print(s_idx );
      out.write("\">&gt;</a>\r\n");
      out.write("						<a href=\"buyContent.jsp?currentPage=");
      out.print(totalPage );
      out.write("&s_idx=");
      out.print(s_idx );
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("						");

					}
					
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div>\r\n");
      out.write("고객문의&nbsp;&nbsp;ezen@gamil.com &nbsp;&nbsp;&nbsp;&nbsp;제휴문의&nbsp;&nbsp;ezen@naver.com\r\n");
      out.write("<br/>\r\n");
      out.write("지역광고&nbsp;&nbsp;ezen@gamil.com\r\n");
      out.write("<br/>\r\n");
      out.write("주소&nbsp;&nbsp;서울특별시 서대문구 신촌로 141 은하빌딩 1층 이젠아카데미 컴퓨터학원\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<div>Copyright &copy; Ezen & 3th. All Rights Reserved.</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
