/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-19 07:17:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import tomato.community.*;
import tomato.community_re.*;

public final class communityContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1633071175604L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1634624681575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("tomato.community");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("tomato.community_re");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      tomato.community.CommunityDAO cdao = null;
      synchronized (session) {
        cdao = (tomato.community.CommunityDAO) _jspx_page_context.getAttribute("cdao", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (cdao == null){
          cdao = new tomato.community.CommunityDAO();
          _jspx_page_context.setAttribute("cdao", cdao, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      tomato.member.MemberDAO mdao = null;
      mdao = (tomato.member.MemberDAO) _jspx_page_context.getAttribute("mdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdao == null){
        mdao = new tomato.member.MemberDAO();
        _jspx_page_context.setAttribute("mdao", mdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

String c_idx_s = request.getParameter("c_idx");
if(c_idx_s == null || c_idx_s.equals("")){
	c_idx_s = "0";
}
int c_idx = Integer.parseInt(c_idx_s);

CommunityDTO dto = cdao.communityContent(c_idx);

if(dto == null){
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.alert('삭제된 게시글 또는 잘못된 접근입니다.');\r\n");
      out.write("	location.href='community.jsp';\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tomato/css/mainLayout.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#joinbtn1{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("}\r\n");
      out.write("#joinbtn1:hover{\r\n");
      out.write("   background: #f5f4f0;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("	background: #f5f4f0;\r\n");
      out.write("	font-family: 'Roboto';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	margin: 0px auto;\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("	text-decoration:none \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comm-hr {\r\n");
      out.write("	border: 1px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".writebtn{\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: tomato;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	height:23px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	margin:2px;\r\n");
      out.write("	border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".writebtn:hover{\r\n");
      out.write("	background-color: tomato;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	height:23px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	margin:2px;\r\n");
      out.write("	border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clicked{\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

int totalCnt = cdao.getTotalCntRe(c_idx); //총 게시물 수
int listSize = 5; //보여줄 리스트 수
int pageSize = 5; //보여줄 페이지 수

String cp_s=request.getParameter("cp");
if(cp_s==null || cp_s.equals("")){
	cp_s="1";
}

int cp = Integer.parseInt(cp_s); //핵심 사용자 위치

int totalPage = (totalCnt/listSize)+1;
if(totalCnt % listSize == 0)totalPage--;

int userGroup = cp/pageSize;
if(cp % pageSize == 0)userGroup--;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkForm() {\r\n");
      out.write("	var form = document.reply;\r\n");
      out.write("	\r\n");
      out.write("	/*댓글 유효성 검사*/\r\n");
      out.write("	if(form.c_r_con.value == null || form.c_r_con.value == \"\"){\r\n");
      out.write("		alert('댓글을 입력해주세요.');\r\n");
      out.write("		form.c_r_con.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}else if(form.c_r_con.value.length<3 || form.c_r_con.value.length>100){\r\n");
      out.write("		alert('댓글은 3-100글자 이내로 입력가능합니다.');\r\n");
      out.write("		form.c_r_con.select();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	form.submit();\r\n");
      out.write("}\r\n");
      out.write("function viewReply(reWrite){\r\n");
      out.write("	if(document.getElementById(reWrite).style.display==\"none\"){\r\n");
      out.write("		document.getElementById(reWrite).style.display=\"block\";\r\n");
      out.write("	}else if(document.getElementById(reWrite).style.display=\"block\"){\r\n");
      out.write("		document.getElementById(reWrite).style.display=\"none\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#btn1{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#btn1:hovertn1{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");

String m_id=(String)session.getAttribute("m_id");
String m_name=(String)session.getAttribute("m_name");
if(m_id==null){
   
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   <a href=\"/tomato/member/login.jsp\">로그인</a> | <a href=\"/tomato/member/join.jsp\">회원가입</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
 
}else{
      
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   ");

   if(m_id.equals("admin")){
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/admin/memberList_admin.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }else{
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/member/mypage.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }
   
      out.write("\r\n");
      out.write("   <a href=\"/tomato/member/logout.jsp\">로그아웃</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");

}

      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><h1><a href=\"/tomato/index.jsp\"><img src=\"/tomato/img/토마토_메인로고.png\" alt=\"메인로고\" height=\"50px\" width=\"250px\"></a></h1></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/sell/sell.jsp\">SELL</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/buy/buyList.jsp?col=s_idx&range=desc\">BUY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/lesson/lessonList.jsp\">LESSON</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/community/community.jsp\">COMMUNITY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/qna/qnaList.jsp\">Q&A</a></h2></li>\r\n");
      out.write("   <li>\r\n");
      out.write("		<form name=\"headerSearch\" action=\"/tomato/buy/headerBuySearch.jsp\" style=\"display: inline;\">\r\n");
      out.write("			<input type=\"text\" name=\"searchValue\" placeholder=\"상품을 검색하세요\">\r\n");
      out.write("			<input type=\"submit\" value=\"검색\" id=\"btn1\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<hr/>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

int m_idx=mdao.selectMidx(m_id);

      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<article>\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"3\" align=\"center\"><h2>");
      out.print(dto.getC_sub() );
      out.write("</h2></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\">작성자: ");
      out.print(dto.getM_name() );
      out.write("</td>\r\n");
      out.write("			<td align=\"right\">\r\n");
      out.write("			");

			if(m_idx != 0 && m_idx == dto.getM_idx()){
			
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("			<a href=\"communityUpdate.jsp?c_idx=");
      out.print(c_idx);
      out.write("\" style=\"color: blue;\">수정하기</a>\r\n");
      out.write("			<a href=\"communityDel_ok.jsp?c_idx=");
      out.print(c_idx);
      out.write("\" style=\"color: red;\">삭제하기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			} else if(m_idx != 0 && m_idx != dto.getM_idx() && m_idx == 1){
			
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("			<a href=\"communityDel_ok.jsp?c_idx=");
      out.print(c_idx);
      out.write("\" style=\"color: red;\">삭제하기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			} 
			
      out.write("\r\n");
      out.write("			작성날짜: ");
      out.print(dto.getC_joindate() );
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"3\" valign=\"top\" align=\"left\" style=\"word-break:break-all;\">");
      out.print(dto.getC_con().replace("\n", "<br>") );
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<hr class=\"comm-hr\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				");

				ArrayList<CommunityReDTO> arr = cdao.communityRe(c_idx ,cp, listSize);
				if(arr==null || arr.size()==0){
				
      out.write("\r\n");
      out.write("				<div style=\"text-align: center;\">등록된 댓글이 없습니다.</div>\r\n");
      out.write("				");

				}else{
					for(int i=0; i<arr.size(); i++){
				
      out.write("\r\n");
      out.write("				<form name=\"communityDel\" action=\"communityReDel_ok.jsp\">\r\n");
      out.write("				<input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"c_r_ref\" value=\"");
      out.print(arr.get(i).getC_r_ref() );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"c_r_lev\" value=\"");
      out.print(arr.get(i).getC_r_lev() );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"c_r_sunbun\" value=\"");
      out.print(arr.get(i).getC_r_sunbun() );
      out.write("\">\r\n");
      out.write("					<div class=\"commnet_box\">\r\n");
      out.write("						<div class=\"comment\">\r\n");
      out.write("						");

						for(int k=0;k<arr.get(i).getC_r_lev();k++){
							out.println("&nbsp;&nbsp;");
						}
						String replyView="reply"+i+"View";
						
      out.write("\r\n");
      out.write("							<span>");
      out.print(arr.get(i).getM_name() );
      out.write(' ');
      out.write(':');
      out.write(' ');
      out.print(arr.get(i).getC_r_con() );
      out.write("</span>\r\n");
      out.write("							");

								if((m_idx == 1 || m_idx == arr.get(i).getM_idx()) && arr.get(i).getC_r_del()==0) {
									
      out.write("\r\n");
      out.write("									<input type=\"submit\" value=\"X\" id=\"joinbtn1\"/>\r\n");
      out.write("									");

								}
								if(m_idx!=0&&arr.get(i).getC_r_del()==0){
									
      out.write("\r\n");
      out.write("									<input type=\"button\" value=\"re\" id=\"joinbtn1\" onclick=\"viewReply('");
      out.print(replyView);
      out.write("');\">\r\n");
      out.write("									");

								}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input name=\"c_r_idx\" type=\"hidden\" value=");
      out.print(arr.get(i).getC_r_idx() );
      out.write(" />\r\n");
      out.write("					<input type=\"hidden\" name=\"c_idx\" value=\"");
      out.print(c_idx );
      out.write("\"/>\r\n");
      out.write("					<div id=\"reply");
      out.print(i );
      out.write("View\" style=\"display: none;\">\r\n");
      out.write("						<table>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("								");

								for(int k=0;k<arr.get(i).getC_r_lev();k++){
									out.println("&nbsp;&nbsp;&nbsp;&nbsp;");
								}
								
      out.write("\r\n");
      out.write("								</td>\r\n");
      out.write("								<td align=\"right\">");
      out.print(m_id );
      out.write("</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<textarea name=\"c_r_con\" rows=\"5\" cols=\"90\" placeholder=\"댓글을 작성해주세요.\"></textarea>\r\n");
      out.write("								</td>\r\n");
      out.write("								<td>\r\n");
      out.write("									<input type=\"submit\" value=\"작성하기\" class=\"writebtn\" formaction=\"communityReRe_ok.jsp\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("				");

				}
			}
				
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<form name=\"reply\" action=\"communityRe_ok.jsp\">\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td align=\"right\">댓글</td>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<br>\r\n");
      out.write("			<br>\r\n");
      out.write("			<input type=\"hidden\" name=\"c_idx\" value=\"");
      out.print(c_idx );
      out.write("\"/>\r\n");
      out.write("			<input type=\"hidden\" name=\"m_idx\" value=\"");
      out.print(m_idx );
      out.write("\"/>\r\n");
      out.write("			<textarea name=\"c_r_con\" rows=\"5\" cols=\"90\" placeholder=\"댓글을 작성해주세요.\"></textarea>\r\n");
      out.write("			</td>\r\n");
      out.write("			\r\n");
      out.write("			<td align=\"left\">\r\n");
      out.write("			<input type=\"button\" value=\"작성하기\" class=\"writebtn\" onclick=\"checkForm()\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"3\" align=\"right\">\r\n");
      out.write("			<a href=\"community.jsp\">목록으로 가기</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("			\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"3\" align=\"center\">\r\n");
      out.write("			<!-- -------------------------페이징 들어갈 영역------------------------------ -->\r\n");
      out.write("		");

			if(userGroup!=0){
				
      out.write("\r\n");
      out.write("				<a href=\"communityContent.jsp?c_idx=");
      out.print(c_idx );
      out.write("&cp=");
      out.print((userGroup-1)*pageSize+pageSize);
      out.write("\">&lt;&lt;</a>\r\n");
      out.write("				");

			}
				
      out.write("\r\n");
      out.write("				");

			for(int i=userGroup*pageSize+1; i<=userGroup*pageSize+pageSize; i++){
			String clickedPage=cp==i?"clicked":"unclicked";
			
      out.write("<label class=\"");
      out.print(clickedPage);
      out.write("\">\r\n");
      out.write("			&nbsp;&nbsp;<a href=\"communityContent.jsp?c_idx=");
      out.print(c_idx );
      out.write("&cp=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>&nbsp;&nbsp;</label>");

			if(i==totalPage){
				break;
			}
			}
				
      out.write("\r\n");
      out.write("				");

			if(userGroup!=(totalPage/pageSize)-(totalPage%pageSize==0?1:0)){
				
      out.write("\r\n");
      out.write("				<a href=\"communityContent.jsp?c_idx=");
      out.print(c_idx );
      out.write("&cp=");
      out.print((userGroup+1)*pageSize+1);
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("				");

		}
		
      out.write("\r\n");
      out.write("			<!-- -------------------------------------------------------------------- -->\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div>\r\n");
      out.write("고객문의&nbsp;&nbsp;ezen@gamil.com &nbsp;&nbsp;&nbsp;&nbsp;제휴문의&nbsp;&nbsp;ezen@naver.com\r\n");
      out.write("<br/>\r\n");
      out.write("지역광고&nbsp;&nbsp;ezen@gamil.com\r\n");
      out.write("<br/>\r\n");
      out.write("주소&nbsp;&nbsp;서울특별시 서대문구 신촌로 141 은하빌딩 1층 이젠아카데미 컴퓨터학원\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<div>Copyright &copy; Ezen & 3th. All Rights Reserved.</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
