/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-19 08:55:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sell;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sell_005fok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1633071175604L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1634624681575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("UTF-8");

      out.write('\r');
      out.write('\n');
      tomato.sell.SellDTO sdto = null;
      synchronized (session) {
        sdto = (tomato.sell.SellDTO) _jspx_page_context.getAttribute("sdto", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sdto == null){
          sdto = new tomato.sell.SellDTO();
          _jspx_page_context.setAttribute("sdto", sdto, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("sdto"), request);
      out.write('\r');
      out.write('\n');
      tomato.sell.SellDAO sdao = null;
      synchronized (session) {
        sdao = (tomato.sell.SellDAO) _jspx_page_context.getAttribute("sdao", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (sdao == null){
          sdao = new tomato.sell.SellDAO();
          _jspx_page_context.setAttribute("sdao", sdao, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

/**상품 등록 후 해당 상품에 대한 s_idx값(sequence) 얻어옴 
CURRVAL의 경우 NEXTVAL 이후 바로 실행*/
int result=sdao.sellProduct(sdto);
if(result<0){
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.alert('제품 등록에 실패하였습니다.');\r\n");
      out.write("	location.href='sell.jsp';\r\n");
      out.write("	</script>	\r\n");
      out.write("	");

}
String id=request.getParameter("m_id");
if(id==null){
	
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.alert('입력시간이 초과되었습니다. 저장된 데이터는 마이페이지에서 수정 가능합니다.');\r\n");
      out.write("	location.href='/tomato/index.jsp';\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	return;
}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("window.alert('상품 등록이 완료되었습니다. 사진을 선택해주세요.');\r\n");
      out.write("</script>\r\n");

String path=id+"/"+result;
sdao.setUserid(path);
sdao.sellFolderExist();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tomato/css/mainLayout.css\">\r\n");
      out.write("<script>\r\n");
      out.write("/**새로고침시 해당 정보 DB에 이중등록되어 새로고침을 막아놓음 */\r\n");
      out.write("function noRefresh(){\r\n");
      out.write("    if (event.keyCode == 116) {\r\n");
      out.write("        alert(\"새로고침을 할 수 없습니다.\");\r\n");
      out.write("        event.keyCode = 2;\r\n");
      out.write("        return false;\r\n");
      out.write("    } \r\n");
      out.write("    else if(event.ctrlKey && (event.keyCode == 78 || event.keyCode == 82))  {\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("document.onkeydown = noRefresh;\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("   background: #f5f4f0;\r\n");
      out.write("   font-family: 'Roboto';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("   width: 700px;\r\n");
      out.write("   margin: 0px auto;\r\n");
      out.write("   margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td{ \r\n");
      out.write("   padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th{\r\n");
      out.write("   padding-right: 25px;\r\n");
      out.write("   padding-bottom: 10px;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("   text-align: right;\r\n");
      out.write("}\r\n");
      out.write(".signup-form {\r\n");
      out.write("   width: 550px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   padding: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-form h3 {\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-size: 40px;\r\n");
      out.write("   margin: 0 0 15px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-form form {\r\n");
      out.write("   border-radius: 1px;\r\n");
      out.write("   margin-bottom: 15px;\r\n");
      out.write("   background: #fff;\r\n");
      out.write("   border: 1px solid #f3f3f3;\r\n");
      out.write("   box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("   padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-form label {\r\n");
      out.write("   font-size: 13px;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height: 23px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sellBtn{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#sellBtn:hover{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write(".fileBtn{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: dimgray;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid teal;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("/**창을 불러올 때 upload1,2,3,4 모두 보이지 않게 처리*/\r\n");
      out.write("function fileSet(){\r\n");
      out.write("	document.getElementById(\"file2\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"file3\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"file4\").style.display=\"none\";\r\n");
      out.write("	document.getElementById(\"file5\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("/**file2 보이게 설정(upload1의 값이 채워져 있을 시에만 실행)*/\r\n");
      out.write("function file2Visible(){\r\n");
      out.write("	if(!document.getElementById(\"upload1\").value==\"\"){\r\n");
      out.write("		document.getElementById(\"file2\").style.display=\"block\";\r\n");
      out.write("	}else{\r\n");
      out.write("		window.alert('파일을 선택해주세요.');\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("/**file2 보이지 않게 설정(해당 파일에 첨부된 사진도 삭제됨.)*/\r\n");
      out.write("function file2inVisible(){\r\n");
      out.write("	document.getElementById(\"upload2\").value=\"\";\r\n");
      out.write("	document.getElementById(\"file2\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("/**file3 보이게 설정(upload1,2의 값이 채워져 있으며 각 파일의 이름이 다를 경우 실행)*/\r\n");
      out.write("function file3Visible(){\r\n");
      out.write("	var filename1=document.getElementById(\"upload1\").value;\r\n");
      out.write("	var filename2=document.getElementById(\"upload2\").value;\r\n");
      out.write("	if(filename1==filename2){\r\n");
      out.write("		window.alert('동일한 파일명의 이미지는 올릴 수 없습니다.');\r\n");
      out.write("	}else if(filename1==null||filename2==null){\r\n");
      out.write("		window.alert('파일을 선택해주세요.');\r\n");
      out.write("	}else{\r\n");
      out.write("		document.getElementById(\"file3\").style.display=\"block\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("/**file3 보이지 않게 설정(해당 파일에 첨부된 사진도 삭제됨.)*/\r\n");
      out.write("function file3inVisible(){\r\n");
      out.write("	document.getElementById(\"upload3\").value=\"\";\r\n");
      out.write("	document.getElementById(\"file3\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("/**file4 보이게 설정(upload1,2,3의 값이 채워져 있으며 각 파일의 이름이 다를 경우 실행)*/\r\n");
      out.write("function file4Visible(){\r\n");
      out.write("	var filename1=document.getElementById(\"upload1\").value;\r\n");
      out.write("	var filename2=document.getElementById(\"upload2\").value;\r\n");
      out.write("	var filename3=document.getElementById(\"upload3\").value;\r\n");
      out.write("	if(filename1==filename2||filename1==filename3||filename2==filename3){\r\n");
      out.write("		window.alert('동일한 파일명의 이미지는 올릴 수 없습니다.');\r\n");
      out.write("	}else if(filename1==null||filename2==null||filename3==null){\r\n");
      out.write("		window.alert('파일을 선택해주세요.');\r\n");
      out.write("	}else{\r\n");
      out.write("		document.getElementById(\"file4\").style.display=\"block\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("/**file4 보이지 않게 설정(해당 파일에 첨부된 사진도 삭제됨.)*/\r\n");
      out.write("function file4inVisible(){\r\n");
      out.write("	document.getElementById(\"upload4\").value=\"\";\r\n");
      out.write("	document.getElementById(\"file4\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("/**file5 보이게 설정(upload1,2,3,4의 값이 채워져 있으며 각 파일의 이름이 다를 경우 실행)*/\r\n");
      out.write("function file5Visible(){\r\n");
      out.write("	var filename1=document.getElementById(\"upload1\").value;\r\n");
      out.write("	var filename2=document.getElementById(\"upload2\").value;\r\n");
      out.write("	var filename3=document.getElementById(\"upload3\").value;\r\n");
      out.write("	var filename4=document.getElementById(\"upload4\").value;\r\n");
      out.write("	if(filename1==filename2||filename1==filename3||filename1==filename4||filename2==filename3||filename2==filename4||filename3==filename4){\r\n");
      out.write("		window.alert('동일한 파일명의 이미지는 올릴 수 없습니다.');\r\n");
      out.write("	}else if(filename1==null||filename2==null||filename3==null||filename4==null){\r\n");
      out.write("		window.alert('파일을 선택해주세요.');\r\n");
      out.write("	}else{\r\n");
      out.write("		document.getElementById(\"file5\").style.display=\"block\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("/**file5 보이지 않게 설정(해당 파일에 첨부된 사진도 삭제됨.)*/\r\n");
      out.write("function file5inVisible(){\r\n");
      out.write("	document.getElementById(\"upload5\").value=\"\";\r\n");
      out.write("	document.getElementById(\"file5\").style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<body onload=\"fileSet()\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#btn1{\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   color: tomato;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("#btn1:hovertn1{\r\n");
      out.write("   background-color: tomato;\r\n");
      out.write("   color: white;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   height:23px;\r\n");
      out.write("   border: none;\r\n");
      out.write("   margin:2px;\r\n");
      out.write("   border: 2px solid tomato;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");

String m_id=(String)session.getAttribute("m_id");
String m_name=(String)session.getAttribute("m_name");
if(m_id==null){
   
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   <a href=\"/tomato/member/login.jsp\">로그인</a> | <a href=\"/tomato/member/join.jsp\">회원가입</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
 
}else{
      
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("   ");

   if(m_id.equals("admin")){
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/admin/memberList_admin.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }else{
      
      out.write("\r\n");
      out.write("      <a href=\"/tomato/member/mypage.jsp\">");
      out.print(m_name );
      out.write("님 마이페이지</a> |\r\n");
      out.write("      ");

   }
   
      out.write("\r\n");
      out.write("   <a href=\"/tomato/member/logout.jsp\">로그아웃</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");

}

      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><h1><a href=\"/tomato/index.jsp\"><img src=\"/tomato/img/토마토_메인로고.png\" alt=\"메인로고\" height=\"50px\" width=\"250px\"></a></h1></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/sell/sell.jsp\">SELL</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/buy/buyList.jsp?col=s_idx&range=desc\">BUY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/lesson/lessonList.jsp\">LESSON</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/community/community.jsp\">COMMUNITY</a></h2></li>\r\n");
      out.write("   <li><h2><a href=\"/tomato/qna/qnaList.jsp\">Q&A</a></h2></li>\r\n");
      out.write("   <li>\r\n");
      out.write("		<form name=\"headerSearch\" action=\"/tomato/buy/headerBuySearch.jsp\" style=\"display: inline;\">\r\n");
      out.write("			<input type=\"text\" name=\"searchValue\" placeholder=\"상품을 검색하세요\">\r\n");
      out.write("			<input type=\"submit\" value=\"검색\" id=\"btn1\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<hr/>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("	<article>\r\n");
      out.write("	<div class=\"signup-form\">\r\n");
      out.write("	<h3>SELL</h3>\r\n");
      out.write("	<!--file이 저장된 multipart/form-data의 경우 form의 input 태그를 통한 parameter 전달 불가능 --- -->\r\n");
      out.write("	<!--path의 경우 사용자의 아이디폴더 안의 상품번호(sequence)폴더로 설정- -->\r\n");
      out.write("		<form name=\"sellImg\" action=\"sellImg_ok.jsp?path=");
      out.print(path );
      out.write("&s_idx=");
      out.print(result );
      out.write("\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th><label>제품명</label></th>\r\n");
      out.write("				<td>");
      out.print(request.getParameter("s_name") );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th><label>가격</label></th>\r\n");
      out.write("				<td>");
      out.print(request.getParameter("s_price") );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th><label>품목</label></th>\r\n");
      out.write("				<td>");
      out.print(request.getParameter("s_cate") );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th><label>제품 설명</label></th>\r\n");
      out.write("				<td style=\"word-break:break-all;\">");
      out.print(request.getParameter("s_con").substring(0,15) );
      out.write("...</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th><label>제품 사진</label></th>\r\n");
      out.write("				<td>\r\n");
      out.write("				<div id=\"file1\">\r\n");
      out.write("					<input type=\"file\" name=\"upload1\" id=\"upload1\" required=\"required\" accept=\".jpg, .jpeg, .png, .JPG, .JPEG\">\r\n");
      out.write("					<input type=\"button\" value=\"+\" onclick=\"file2Visible()\" class=\"fileBtn\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"file2\">\r\n");
      out.write("					<input type=\"file\" name=\"upload2\" id=\"upload2\" accept=\".jpg, .jpeg, .png, .JPG, .JPEG\">\r\n");
      out.write("					<input type=\"button\" value=\"+\" onclick=\"file3Visible()\" class=\"fileBtn\">\r\n");
      out.write("					<input type=\"button\" value=\"-\" onclick=\"file2inVisible()\" class=\"fileBtn\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"file3\">\r\n");
      out.write("					<input type=\"file\" name=\"upload3\" id=\"upload3\" accept=\".jpg, .jpeg, .png, .JPG, .JPEG\">\r\n");
      out.write("					<input type=\"button\" value=\"+\" onclick=\"file4Visible()\" class=\"fileBtn\">\r\n");
      out.write("					<input type=\"button\" value=\"-\" onclick=\"file3inVisible()\" class=\"fileBtn\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"file4\">\r\n");
      out.write("					<input type=\"file\" name=\"upload4\" id=\"upload4\" accept=\".jpg, .jpeg, .png, .JPG, .JPEG\">\r\n");
      out.write("					<input type=\"button\" value=\"+\" onclick=\"file5Visible()\" class=\"fileBtn\">\r\n");
      out.write("					<input type=\"button\" value=\"-\" onclick=\"file4inVisible()\" class=\"fileBtn\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"file5\">\r\n");
      out.write("					<input type=\"file\" name=\"upload5\" id=\"upload5\" accept=\".jpg, .jpeg, .png, .JPG, .JPEG\">\r\n");
      out.write("					<input type=\"button\" value=\"-\" onclick=\"file5inVisible()\" class=\"fileBtn\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<h6 style=\"display:inline;\">.jpg, .png .jpeg만 가능</h6>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<div style=\"text-align:center;\">\r\n");
      out.write("				<input type=\"submit\" value=\"등록하기\" id=\"sellBtn\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>	\r\n");
      out.write("	</article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div>\r\n");
      out.write("고객문의&nbsp;&nbsp;ezen@gamil.com &nbsp;&nbsp;&nbsp;&nbsp;제휴문의&nbsp;&nbsp;ezen@naver.com\r\n");
      out.write("<br/>\r\n");
      out.write("지역광고&nbsp;&nbsp;ezen@gamil.com\r\n");
      out.write("<br/>\r\n");
      out.write("주소&nbsp;&nbsp;서울특별시 서대문구 신촌로 141 은하빌딩 1층 이젠아카데미 컴퓨터학원\r\n");
      out.write("</div>\r\n");
      out.write("<br/>\r\n");
      out.write("<div>Copyright &copy; Ezen & 3th. All Rights Reserved.</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
